local addonName = ...

local LSM = LibStub("LibSharedMedia-3.0")
local koKR, ruRU, zhCN, zhTW, western = LSM.LOCALE_BIT_koKR, LSM.LOCALE_BIT_ruRU, LSM.LOCALE_BIT_zhCN, LSM.LOCALE_BIT_zhTW, LSM.LOCALE_BIT_western
local mediaRoot = ([[Interface\AddOns\%s\media\]]):format(addonName)
local legacyMediaRoot = [[Interface\AddOns\LizeUI\media\]]

local function Media(relativePath)
	return mediaRoot .. relativePath
end

if LSM == nil then return end

local sharedMediaRegister = LSM.Register

function LSM:Register(mediaType, key, data, ...)
	if type(data) == 'string' and data:sub(1, #legacyMediaRoot) == legacyMediaRoot then
		data = mediaRoot .. data:sub(#legacyMediaRoot + 1)
	end

	return sharedMediaRegister(self, mediaType, key, data, ...)
end

LSM:Register("font","GothamNarrowUltra", Media("fonts\\GothamNarrowUltra.ttf"),				ruRU + western)
LSM:Register("font","LizeUI Regular", Media("fonts\\AvantGardeLT-Regular.ttf"))
LSM:Register("font","LizeUI Medium", Media("fonts\\AvantGardeLT-Medium.ttf"))
LSM:Register("font","LizeUI Bold", Media("fonts\\AvantGardeLT-Bold.ttf"))
LSM:Register("font","LizeUI Demi", Media("fonts\\AvantGardeLT-Demi.ttf"))
LSM:Register("font","LizeUI Numbers", Media("fonts\\AvantGardeLT-Numbers.ttf"),							ruRU + western)
LSM:Register("font","Naowh", Media("fonts\\AvantGardeLT-Demi.ttf"))
LSM:Register("font","Bui Prototype", Media("fonts\\PROTOTYPE.TTF"))
LSM:Register("font","Bui PrototypeRU", Media("fonts\\PROTOTYPE_RU.TTF"))
LSM:Register("font","Bui Visitor1", Media("fonts\\visitor1.ttf"))
LSM:Register("font","Bui Visitor2", Media("fonts\\visitor2.ttf"))
LSM:Register("font","Bui Tukui", Media("fonts\\uf_font.ttf"))
LSM:Register("font","Bui Kait", Media("fonts\\heavy_dock_kait.ttf"))
LSM:Register("font","Bui ArialN", Media("fonts\\ARIALN.ttf"))
LSM:Register("font","Bui Homizio", Media("fonts\\homizio_bold.ttf"))
LSM:Register("font","Bui FiraBold", Media("fonts\\FiraSansCondensed-Bold.ttf"))
LSM:Register("font","JetBrainsMono Medium", Media("fonts\\JetBrainsMono-Medium.ttf"))
LSM:Register("font","JetBrainsMono Regular", Media("fonts\\JetBrainsMono-Regular.ttf"))
LSM:Register("font","JetBrains SemiBold", Media("fonts\\JetBrainsMono-SemiBold.ttf"))
LSM:Register("font","JetBrainsMono-Bold", Media("fonts\\JetBrainsMono-Bold.ttf"))
LSM:Register("font","Montserrat", Media("fonts\\Montserrat.ttf"),							ruRU + western)

LSM:Register("sound", "1 -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\1 -Naowh.ogg]])
LSM:Register("sound", "2 -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\2 -Naowh.ogg]])
LSM:Register("sound", "3 -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\3 -Naowh.ogg]])
LSM:Register("sound", "4 -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\4 -Naowh.ogg]])
LSM:Register("sound", "5 -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\5 -Naowh.ogg]])
LSM:Register("sound", "6 -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\6 -Naowh.ogg]])
LSM:Register("sound", "7 -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\7 -Naowh.ogg]])
LSM:Register("sound", "8 -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\8 -Naowh.ogg]])
LSM:Register("sound", "9 -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\9 -Naowh.ogg]])
LSM:Register("sound", "10 -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\10 -Naowh.ogg]])
LSM:Register("sound", "Absorb -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Absorb -Naowh.ogg]])
LSM:Register("sound", "Add -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Add -Naowh.ogg]])
LSM:Register("sound", "Adds -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Adds -Naowh.ogg]])
LSM:Register("sound", "AoE -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\AoE -Naowh.ogg]])
LSM:Register("sound", "Avoid -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Avoid -Naowh.ogg]])
LSM:Register("sound", "Bait -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Bait -Naowh.ogg]])
LSM:Register("sound", "Beam -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Beam -Naowh.ogg]])
LSM:Register("sound", "Behind -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Behind -Naowh.ogg]])
LSM:Register("sound", "Bloodlust -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Bloodlust -Naowh.ogg]])
LSM:Register("sound", "Bomb -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Bomb -Naowh.ogg]])
LSM:Register("sound", "Breath -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Breath -Naowh.ogg]])
LSM:Register("sound", "Buff -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Buff -Naowh.ogg]])
LSM:Register("sound", "CC -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\CC -Naowh.ogg]])
LSM:Register("sound", "Charge -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Charge -Naowh.ogg]])
LSM:Register("sound", "Clear In -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Clear In -Naowh.ogg]])
LSM:Register("sound", "Clear -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Clear -Naowh.ogg]])
LSM:Register("sound", "Collect -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Collect -Naowh.ogg]])
LSM:Register("sound", "Combat -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Combat -Naowh.ogg]])
LSM:Register("sound", "Dance -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Dance -Naowh.ogg]])
LSM:Register("sound", "Debuff -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Debuff -Naowh.ogg]])
LSM:Register("sound", "Destroy -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Destroy -Naowh.ogg]])
LSM:Register("sound", "Dispell -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Dispell -Naowh.ogg]])
LSM:Register("sound", "Dodge Inc -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Dodge Inc -Naowh.ogg]])
LSM:Register("sound", "Dodge -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Dodge -Naowh.ogg]])
LSM:Register("sound", "Dot -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Dot -Naowh.ogg]])
LSM:Register("sound", "External -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\External -Naowh.ogg]])
LSM:Register("sound", "Fixate -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Fixate -Naowh.ogg]])
LSM:Register("sound", "Freedom -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Freedom -Naowh.ogg]])
LSM:Register("sound", "Frontal -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Frontal -Naowh.ogg]])
LSM:Register("sound", "Green -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Green -Naowh.ogg]])
LSM:Register("sound", "Hide -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Hide -Naowh.ogg]])
LSM:Register("sound", "High Stacks -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\High Stacks -Naowh.ogg]])
LSM:Register("sound", "Immune -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Immune -Naowh.ogg]])
LSM:Register("sound", "In -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\In -Naowh.ogg]])
LSM:Register("sound", "Inc -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Inc -Naowh.ogg]])
LSM:Register("sound", "Inside -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Inside -Naowh.ogg]])
LSM:Register("sound", "Intermission -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Intermission -Naowh.ogg]])
LSM:Register("sound", "Kick -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Kick -Naowh.ogg]])
LSM:Register("sound", "Knock -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Knock -Naowh.ogg]])
LSM:Register("sound", "Left -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Left -Naowh.ogg]])
LSM:Register("sound", "Linked -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Linked -Naowh.ogg]])
LSM:Register("sound", "LoS -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\LoS -Naowh.ogg]])
LSM:Register("sound", "LostVikings -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\LongboatRaid.ogg]])
LSM:Register("sound", "Lorgok Boss Dmg -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Lorgok_BossDmg.ogg]])
LSM:Register("sound", "Lorgok Burp -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Lorgok_Burp.ogg]])
LSM:Register("sound", "Lorgok Doesnt Happen -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Lorgok_DoesntHappen.ogg]])
LSM:Register("sound", "Lorgok Ejaculate -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Lorgok_Ejaculate.ogg]])
LSM:Register("sound", "Lorgok Help -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Lorgok_Help.ogg]])
LSM:Register("sound", "Lorgok Noooo -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Lorgok_Noooo.ogg]])
LSM:Register("sound", "Lorgok Oh What -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Lorgok_OhWhat.ogg]])
LSM:Register("sound", "Lorgok Ok Bro -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Lorgok_OkBro.ogg]])
LSM:Register("sound", "Lorgok Oribole -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Lorgok_Oribole.ogg]])
LSM:Register("sound", "Lorgok Stupid Dude -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Lorgok_StupidDude.ogg]])
LSM:Register("sound", "Lorgok WTF -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Lorgok_WTF.ogg]])
LSM:Register("sound", "Lorgok Yeah -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Lorgok_Yeah.ogg]])
LSM:Register("sound", "Melee -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Melee -Naowh.ogg]])
LSM:Register("sound", "Mount -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Mount -Naowh.ogg]])
LSM:Register("sound", "Move -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Move -Naowh.ogg]])
LSM:Register("sound", "Next -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Next -Naowh.ogg]])
LSM:Register("sound", "Nuke -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Nuke -Naowh.ogg]])
LSM:Register("sound", "Orb -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Orb -Naowh.ogg]])
LSM:Register("sound", "Orbs -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Orbs -Naowh.ogg]])
LSM:Register("sound", "Out -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Out -Naowh.ogg]])
LSM:Register("sound", "Outrange -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Outrange -Naowh.ogg]])
LSM:Register("sound", "Personal -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Personal -Naowh.ogg]])
LSM:Register("sound", "Pot -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Pot -Naowh.ogg]])
LSM:Register("sound", "Pull -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Pull -Naowh.ogg]])
LSM:Register("sound", "Push -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Push -Naowh.ogg]])
LSM:Register("sound", "Ranged -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Ranged -Naowh.ogg]])
LSM:Register("sound", "Ready -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Ready -Naowh.ogg]])
LSM:Register("sound", "Red -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Red -Naowh.ogg]])
LSM:Register("sound", "Reflect -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Reflect -Naowh.ogg]])
LSM:Register("sound", "Right -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Right -Naowh.ogg]])
LSM:Register("sound", "Run -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Run -Naowh.ogg]])
LSM:Register("sound", "Sac -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Sac -Naowh.ogg]])
LSM:Register("sound", "Shield -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Shield -Naowh.ogg]])
LSM:Register("sound", "Soak -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Soak -Naowh.ogg]])
LSM:Register("sound", "Spike -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Spike -Naowh.ogg]])
LSM:Register("sound", "Spread -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Spread -Naowh.ogg]])
LSM:Register("sound", "Stack -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Stack -Naowh.ogg]])
LSM:Register("sound", "Stop -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Stop -Naowh.ogg]])
LSM:Register("sound", "Stopcast -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Stopcast -Naowh.ogg]])
LSM:Register("sound", "Switch -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Switch -Naowh.ogg]])
LSM:Register("sound", "Taunt -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Taunt -Naowh.ogg]])
LSM:Register("sound", "Totem -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Totem -Naowh.ogg]])
LSM:Register("sound", "Trap -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Trap -Naowh.ogg]])
LSM:Register("sound", "Turn -Naowh", [[Interface\AddOns\LizeUI\media\sounds\naowh\Turn -Naowh.ogg]])

LSM:Register("statusbar","AsphyxiaNorm", [[Interface\AddOns\LizeUI\media\textures\statusbar\AsphyxiaNorm.tga]])
LSM:Register("statusbar","BuiOnePixel", [[Interface\AddOns\LizeUI\media\textures\statusbar\BuiOnePixel.tga]])
LSM:Register("statusbar","Dragonflight01", [[Interface\AddOns\LizeUI\media\textures\statusbar\Dragonflight01.tga]])
LSM:Register("statusbar","Dragonflight02", [[Interface\AddOns\LizeUI\media\textures\statusbar\Dragonflight02.tga]])
LSM:Register("statusbar","Dragonflight03", [[Interface\AddOns\LizeUI\media\textures\statusbar\Dragonflight03.tga]])
LSM:Register("statusbar","Eltreum-20pc", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-20pc.tga]])
LSM:Register("statusbar","Eltreum-30pc", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-30pc.tga]])
LSM:Register("statusbar","Eltreum-Blank", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-Blank.tga]])
LSM:Register("statusbar","Eltreum-bottom", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-bottom.tga]])
LSM:Register("statusbar","Eltreum-Dark", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-Dark.tga]])
LSM:Register("statusbar","Eltreum-DH", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-DH.tga]])
LSM:Register("statusbar","Eltreum-DHv2", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-DHv2.tga]])
LSM:Register("statusbar","Eltreum-DHv3", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-DHv3.tga]])
LSM:Register("statusbar","Eltreum-Diagonal", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-Diagonal.tga]])
LSM:Register("statusbar","Eltreum-DK", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-DK.tga]])
LSM:Register("statusbar","Eltreum-DKv2", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-DKv2.tga]])
LSM:Register("statusbar","Eltreum-DKv3", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-DKv3.tga]])
LSM:Register("statusbar","Eltreum-DR", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-DR.tga]])
LSM:Register("statusbar","Eltreum-DRv2", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-DRv2.tga]])
LSM:Register("statusbar","Eltreum-DRv3", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-DRv3.tga]])
LSM:Register("statusbar","Eltreum-Elvui-Norm", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-Elvui-Norm.tga]])
LSM:Register("statusbar","Eltreum-EV", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-EV.tga]])
LSM:Register("statusbar","Eltreum-EVv2", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-EVv2.tga]])
LSM:Register("statusbar","Eltreum-EVv3", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-EVv3.tga]])
LSM:Register("statusbar","Eltreum-HT", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-HT.tga]])
LSM:Register("statusbar","Eltreum-HTv2", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-HTv2.tga]])
LSM:Register("statusbar","Eltreum-HTv3", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-HTv3.tga]])
LSM:Register("statusbar","Eltreum-left", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-left.tga]])
LSM:Register("statusbar","Eltreum-MG", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-MG.tga]])
LSM:Register("statusbar","Eltreum-MGv2", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-MGv2.tga]])
LSM:Register("statusbar","Eltreum-MGv3", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-MGv3.tga]])
LSM:Register("statusbar","Eltreum-MK", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-MK.tga]])
LSM:Register("statusbar","Eltreum-MKv2", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-MKv2.tga]])
LSM:Register("statusbar","Eltreum-MKv3", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-MKv3.tga]])
LSM:Register("statusbar","Eltreum-PL", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-PL.tga]])
LSM:Register("statusbar","Eltreum-PLv2", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-PLv2.tga]])
LSM:Register("statusbar","Eltreum-PLv3", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-PLv3.tga]])
LSM:Register("statusbar","Eltreum-PR", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-PR.tga]])
LSM:Register("statusbar","Eltreum-PRv2", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-PRv2.tga]])
LSM:Register("statusbar","Eltreum-PRv3", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-PRv3.tga]])
LSM:Register("statusbar","Eltreum-RG", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-RG.tga]])
LSM:Register("statusbar","Eltreum-RGv2", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-RGv2.tga]])
LSM:Register("statusbar","Eltreum-RGv3", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-RGv3.tga]])
LSM:Register("statusbar","Eltreum-right", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-right.tga]])
LSM:Register("statusbar","Eltreum-SH", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-SH.tga]])
LSM:Register("statusbar","Eltreum-SHv2", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-SHv2.tga]])
LSM:Register("statusbar","Eltreum-SHv3", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-SHv3.tga]])
LSM:Register("statusbar","Eltreum-Stripes", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-Stripes.tga]])
LSM:Register("statusbar","Eltreum-Stripes2", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-Stripes2.tga]])
LSM:Register("statusbar","Eltreum-Stripes3", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-Stripes3.tga]])
LSM:Register("statusbar","Eltreum-Stripes4", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-Stripes4.tga]])
LSM:Register("statusbar","Eltreum-Tapped", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-Tapped.tga]])
LSM:Register("statusbar","Eltreum-Tappedv2", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-Tappedv2.tga]])
LSM:Register("statusbar","Eltreum-Tappedv3", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-Tappedv3.tga]])
LSM:Register("statusbar","Eltreum-top", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-top.tga]])
LSM:Register("statusbar","Eltreum-Transparent", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-Transparent.tga]])
LSM:Register("statusbar","Eltreum-WA", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-WA.tga]])
LSM:Register("statusbar","Eltreum-WAv2", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-WAv2.tga]])
LSM:Register("statusbar","Eltreum-WAv3", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-WAv3.tga]])
LSM:Register("statusbar","Eltreum-WL", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-WL.tga]])
LSM:Register("statusbar","Eltreum-WLv2", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-WLv2.tga]])
LSM:Register("statusbar","Eltreum-WLv3", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum-WLv3.tga]])
LSM:Register("statusbar","Eltreum10pixel", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum10pixel.tga]])
LSM:Register("statusbar","Eltreum1pixel", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum1pixel.tga]])
LSM:Register("statusbar","Eltreum2pixel", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum2pixel.tga]])
LSM:Register("statusbar","Eltreum3pixel", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum3pixel.tga]])
LSM:Register("statusbar","Eltreum4pixel", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum4pixel.tga]])
LSM:Register("statusbar","Eltreum5pixel", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum5pixel.tga]])
LSM:Register("statusbar","Eltreum6pixel", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum6pixel.tga]])
LSM:Register("statusbar","Eltreum7pixel", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum7pixel.tga]])
LSM:Register("statusbar","Eltreum7pixelB", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum7pixelB.tga]])
LSM:Register("statusbar","Eltreum8pixel", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum8pixel.tga]])
LSM:Register("statusbar","Eltreum9pixel", [[Interface\AddOns\LizeUI\media\textures\statusbar\Eltreum9pixel.tga]])
LSM:Register("statusbar","EltreumFade", [[Interface\AddOns\LizeUI\media\textures\statusbar\EltreumFade.tga]])
LSM:Register("statusbar","Empty", [[Interface\AddOns\LizeUI\media\textures\statusbar\Empty.tga]])
LSM:Register("statusbar","Flat", [[Interface\AddOns\LizeUI\media\textures\statusbar\Flat.tga]])
LSM:Register("statusbar","Kait1", [[Interface\AddOns\LizeUI\media\textures\statusbar\Kait1.tga]])
LSM:Register("statusbar","Kait2", [[Interface\AddOns\LizeUI\media\textures\statusbar\Kait2.tga]])
LSM:Register("statusbar","KMT32", [[Interface\AddOns\LizeUI\media\textures\statusbar\KMT32.tga]])
LSM:Register("statusbar","Melli", [[Interface\AddOns\LizeUI\media\textures\statusbar\Melli.tga]])
LSM:Register("statusbar","MelliDark", [[Interface\AddOns\LizeUI\media\textures\statusbar\MelliDark.tga]])
LSM:Register("statusbar","None", [[Interface\AddOns\LizeUI\media\textures\statusbar\None.tga]])
LSM:Register("statusbar","pHishTex29", [[Interface\AddOns\LizeUI\media\textures\statusbar\pHishTex29.tga]])
LSM:Register("statusbar","pHishTex35", [[Interface\AddOns\LizeUI\media\textures\statusbar\pHishTex35.tga]])
LSM:Register("statusbar","pHishTex5", [[Interface\AddOns\LizeUI\media\textures\statusbar\pHishTex5.tga]])

LSM.Register = sharedMediaRegister
